### ISSUE TITLE
DNS errors with HostNetwork and ClusterFirstWithHostNet settings

### ISSUE THREAD

**Issue by cakrit** [netdata/helmchart#95]
Hi All @cakrit @ilyam8  @zack-shoylev @thiagoftsm @vlvkobal 

Here is what we found to debug connectivity and streaming problem:
The Helm chart installs netdata with dnsPolicy: ClusterFirstWithHostNet, which causes DNS errors, making slave - master streaming haphazard (even without encrypting streaming, or influxdb backend). Setting it to ClusterFirst solves the problem, but we are afraid that we lose some of the metrics.

_Originally posted by @Peggy4444 in https://github.com/netdata/netdata/issues/8847#issuecomment-623980514_

**Comment by cakrit** [comment]
I'm not sure why we would need these two settings in our Daemonset, they were in the original chart @varyumin had created. I'm doing a PR without them that I tested and didn't see anything wrong with streaming, or with the network interfaces. Before we merge though, let's hear from @varyumin

**Comment by varyumin** [comment]
My opinion. Why I have picked DNS Policy `ClusterFirstWithHostNet`, because used `hostNetwork` (IMPORTANT) and in Kubernetes documents are written   "For Pods running with `hostNetwork`, you should explicitly set its DNS policy “ClusterFirstWithHostNet”" https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy . What is it means for me? If I want something monitoring outside of Kubernetes with FQDN (example www.kubernetes.io), I have to try to resolve a hostname inside Kubernetes DNS server (core-dns, kube-dns) and after pass to host DNS server. If I will use another policy I never resolve external hostnames inside my cluster.
And we have to set a clear DNS policy. The DNS policy `Default` value is not appropriate, because the behavior DNS server depends on settings cluster Kubernetes.
Maybe I am wrong but not sure ))

**Comment by varyumin** [comment]
If you don't need `hostNetwork`. U can remove hostNetwork: true and DNS Policy

**Comment by varyumin** [comment]
I would stay this as an option in helm chart

**Comment by cakrit** [comment]
Ok, we'll make these two configurable. I will close the open PR and do a new one.

**Comment by ilyam8** [comment]
Fixed in #234, both those options are configurable now.
